### ISSUE TITLE
009

### ISSUE THREAD

**Issue by elliotwoods** [liquidzym/openframeworks_X64#2]
Hey there

I've been using a modified version of this branch for my own work.
Thank you!

I'm wondering if you've looked into developing an oF-009 compatible version (to keep it up to date with recent changes in the core).

Also I've had some issues with OSC and this branch. Did you experience that yourself at all?

Elliot

**Comment by liquidzym** [comment]
hey,Elliot,sorry not keep it update yet with 090,waiting for the apothecary formulas see whether can complied the cairo as 64 libs currently its missing.
yeah,i think you're right,got some issues with OSC myself, as far as i recalled i just changed this line 

#ifndef **x86_64**
as #if !(defined(**x86_64**) || defined(_M_X64))
in OscOutboundPacketStream.h line 99
not too sure you had same issue as well?

cheers
alex

**Comment by elliotwoods** [comment]
i'd been getting some symbol errors, can't remember what exactly. but hit it in a couple of situations.

in the end i switched to oskpkt for this project (it's small, had a few issues with c++11 but easy to fix)
